apiVersion : apps/v1
kind: Deployment
metadata:
  name: <deployment_name>
  namespace: app-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: <deployment_name>
  template:
    metadata:
      labels:
        app: <deployment_name>
    spec:
      containers:
        - name: <deployment_name>
          image: <acr_server>/dx29segmentation
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 0.23
              memory: "256Mi"
